# START OMIT
apiVersion: v1
kind: Service
metadata: 
  name: my-service
spec:
  selector: 
    app : my-app
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
# END OMIT
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: my-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - image: nginx
        imagePullPolicy: Always
        name: nginx
        ports:
        - containerPort: 8080
