apiVersion: v1
kind: Service
metadata:
  name: my-svc-nodeport
# START OMIT
spec:
  type: NodePort        
  ports:
  - port: 80          
    targetPort: 8080  
    nodePort: 30123
  selector:
    app: my-app
# END OMIT