kind: Pod
apiVersion: v1
metadata:
  name: prod-db-client-pod
  labels:
    name: prod-db-client
spec:
  # START OMIT
  serviceAccount: prod-db-client
  containers:
  - name: db-client-container
    image: myClientImage
  # END OMIT